change svn-get_root_urls: use current url if url not given
git-svn-id: https://svn-user-sacks.cgd.ucar.edu/bin/trunk@558 81eb0212-1297-45d0-9317-8d7c8fb0914c

diff --git a/svn-get_root_urls b/svn-get_root_urls
--- a/svn-get_root_urls
+++ b/svn-get_root_urls
@@ -16,7 +16,7 @@
 # Note 12-25-11: this script has some commonality with part of
 # svn-make_cesm_branch
 # 
-# Usage: svn-get_root_urls URL
+# Usage: svn-get_root_urls [-u URL]
 #
 # Returns two space-delimited strings: either:
 # (a) trunk_url trunk_tags_url
@@ -29,19 +29,49 @@
 
 function Usage {
     progname=`basename $0`
-    echo "Usage: $progname URL"
+    echo "Usage: $progname [-h] [-u URL]"
+    echo ""
+    echo "If URL isn't given, it is obtained with svn-url"
 }
 
 # ----------------------------------------------------------------------
 # BEGIN MAIN SCRIPT
 # ----------------------------------------------------------------------
 
-if [[ $# -ne 1 ]]; then
+url=""
+
+while getopts hu: opt; do
+    case $opt in
+	h) Usage; exit;;
+	u) url=$OPTARG;;
+	\?) Usage; exit 1
+    esac
+done
+
+# shift off the arguments we read with getopts:
+shift `expr $OPTIND - 1`
+
+if [[ $# -ne 0 ]]; then
     Usage
     exit 1
 fi
 
-url=$1
+# ----------------------------------------------------------------------
+# If URL isn't specified, get current URL from svn
+# ----------------------------------------------------------------------
+
+if [ -z "$url" ]; then
+    url=`svn-url`
+    if [ $? -ne 0 ]; then
+	# for non-zero return value, url holds the error string
+	echo $url
+	exit 1
+    fi
+fi
+
+# ----------------------------------------------------------------------
+# Get roots
+# ----------------------------------------------------------------------
 
 root=$url
 cur_base=''
